#pragma once

// Configuration for tsb1

#define RETARGET_SPI_UART      USART1
#define RETARGET_SPI_CLOCK     cmuClock_USART1
#define RETARGET_SPI_MISO_PORT gpioPortC
#define RETARGET_SPI_MISO_PIN  7
#define RETARGET_SPI_MOSI_PORT gpioPortC
#define RETARGET_SPI_MOSI_PIN  6
#define RETARGET_SPI_SCK_PORT  gpioPortC
#define RETARGET_SPI_SCK_PIN   8
#define RETARGET_SPI_CS_PORT   gpioPortA
#define RETARGET_SPI_CS_PIN    4
#define RETARGET_SPI_RX_LOC    USART_ROUTELOC0_RXLOC_LOC11
#define RETARGET_SPI_TX_LOC    USART_ROUTELOC0_TXLOC_LOC11
#define RETARGET_SPI_CLK_LOC   USART_ROUTELOC0_CLKLOC_LOC11
