#pragma once

// Configuration for tsb0

#define RETARGET_SPI_UART      USART3
#define RETARGET_SPI_CLOCK     cmuClock_USART3
#define RETARGET_SPI_MISO_PORT gpioPortD
#define RETARGET_SPI_MISO_PIN  15
#define RETARGET_SPI_MOSI_PORT gpioPortD
#define RETARGET_SPI_MOSI_PIN  12
#define RETARGET_SPI_SCK_PORT  gpioPortD
#define RETARGET_SPI_SCK_PIN   13
#define RETARGET_SPI_CS_PORT   gpioPortD
#define RETARGET_SPI_CS_PIN    14
#define RETARGET_SPI_RX_LOC    USART_ROUTELOC0_RXLOC_LOC6
#define RETARGET_SPI_TX_LOC    USART_ROUTELOC0_TXLOC_LOC4
#define RETARGET_SPI_CLK_LOC   USART_ROUTELOC0_CLKLOC_LOC3
